### PR TITLE
Use Ragel to Parse the Version Information

### PR DESCRIPTION
**Pull request by pope**
I was able to eke out the slightest bit more performance by using Ragel to do the parsing. I offer it back if using another tool doesn't solve more problems than it causes.

I also fixed a few warnings while I was in there.

### CODE REVIEW

**Comment by mislav** [comment]
Interesting! But if it's only a "slightest bit" more performance, I feel that it's not worth risking a huge change. Version sorting isn't a performance problem right now on GitHub.com like when it was when it was implemented in Ruby.

Do you mind sharing the `script/benchmark` output?

**Comment by mislav** [comment]
Also, both files now say “Created with Ragel.” This can't be true, as one file is definitely generated, and one file is Ragel source. Which is which?

**Comment by pope** [comment]
Yeah, totally agree that this isn't something you *need*. I was just porting over some version parsing work that I did elsewhere with a similar ragel machine and saw that it sped this up.

After I re-record the benchmarks locally.

```
VersionSorter .sort
  Baseline: |                                                              X---|
  Current:  |                                                           X----  |
            0                                                         488.953 us

VersionSorter .rsort
  Baseline: |                                                             X--  |
  Current:  |                                                          X-------|
            0                                                         509.559 us
```

I agree with the double "Created with Ragel" stuff. Would you accept a README file in that directory?

**Comment by mislav** [comment]
Thanks for sharing the benchmark. You were right that the speedup is only minor. I don't think it warrants the significant change to the codebase. Thank you for suggesting, though!

**Comment by pope** [comment]
Yup. Thanks for considering. I get it that the risk/reward isn't great, but thought I would share it back. Cheers.

**Comment by mislav** [comment]
It's always interesting to see neat uses for Ragel. One other project that I found really interesting was a [vim keystroke parser written in Ragel](https://github.com/nelstrom/vimprint/blob/master/ext/ragel/parser.rl).

**Pull request closed without merging**
