### PR TITLE
Add optional block to allow sorting of arrays of arbitrary objects

### PR DESCRIPTION
**Pull request by eReGeBe**
Implementation for https://github.com/github/version_sorter/issues/9

### CODE REVIEW

**Comment by mislav** [comment]
Looks good! But I'm not sure if `sort` and `rsort` should accept an optional block. Maybe make a separate method called `sort_by`? Just an idea; you don't have to make the actual code change yet.

@tmm1 @vmg What do you think?

**Comment by eReGeBe** [comment]
I think you can make the parallel with `Enumerable#sort`, which takes an optional block. `Enumerable#sort_by` on the other hand uses the block to map elements, which is what `VersionSorter` does internally (map a string to a version struct). So I think following the enumerable template, here we want `sort` with an optional block, and not `sort_by`.

Doc: http://ruby-doc.org/core-2.3.1/Enumerable.html#method-i-sort

**Comment by eReGeBe** [comment]
Any update on this PR?

**Comment by eReGeBe** [comment]
Just pinging again to check for this PR.

**Comment by mislav** [comment]
Thanks! Sorry for the late reply.

**Comment by eReGeBe** [comment]
Great! Thanks.

**Pull request merged**
