### PR TITLE
Enable travis

### PR DESCRIPTION
**Pull request by vmg**
Let's see if we can get this to build on as many platforms as possible.

cc @mislav

### CODE REVIEW

**Comment by mislav** [comment]
Nice! You're a miracle worker. Now it seems to fail on 1.8 only because I've used `sample()`.

**Comment by mislav** [comment]
What prompted you to add the bang equivalents?

**Comment by vmg** [comment]
It occurred to me that `sort!` could be implemented **very** efficiently (and with less code), so I thought I would do just that and then implement `sort` by calling `dup` and `sort!` (this is how `Array#sort!` implemented in MRI and makes a lot of sense to me).

**Comment by mislav** [comment]
Sure. I can add tests for the new methods, no prob. I can also switch away from `sample` if you feel like you're done with this. You've already helped more than enough! :bow:

**Comment by vmg** [comment]
I'd rather remove 1.8.7 support, it's such a security risk! But if you're set on legacy support, feel free to fix the `sample` tests, I won't complain :))

**Comment by mislav** [comment]
If we would be able to remove a bunch of C code if we dropped support for 1.8, then I would be up for it. But if it's the same to us either way, then let's keep it since the previous version had it.

**Comment by vmg** [comment]
Nah, the code will remain the same. Go ahead and fix the tests then -- I think this is ready to work everywhere.

**Pull request merged**
